/**
 * Central registry of error codes returned by calc-engine.
 * Consuming apps should branch on `code`, not on `message` text
 * (message text is for humans and may be reworded over time).
 */
export const ErrorCodes = Object.freeze({
  DIVISION_BY_ZERO: 'DIVISION_BY_ZERO',
  INVALID_EXPRESSION: 'INVALID_EXPRESSION',
  INVALID_PARENTHESES: 'INVALID_PARENTHESES',
  INVALID_CHARACTER: 'INVALID_CHARACTER',
  INVALID_NUMBER: 'INVALID_NUMBER',
  INVALID_LOG: 'INVALID_LOG',
  INVALID_SQRT: 'INVALID_SQRT',
  FACTORIAL_OVERFLOW: 'FACTORIAL_OVERFLOW',
  FACTORIAL_INVALID: 'FACTORIAL_INVALID',
  UNKNOWN_FUNCTION: 'UNKNOWN_FUNCTION',
  RESULT_INFINITY: 'RESULT_INFINITY',
  RESULT_NAN: 'RESULT_NAN',
  MISSING_ELEMENT: 'MISSING_ELEMENT',
  INVALID_CONFIG: 'INVALID_CONFIG',
  EMPTY_EXPRESSION: 'EMPTY_EXPRESSION',
  CLIPBOARD_ERROR: 'CLIPBOARD_ERROR',
  NOT_INITIALIZED: 'NOT_INITIALIZED'
});
